# Generated by Django 3.0.1 on 2020-01-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200120_1949'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, to='shop.ProductInCart'),
        ),
    ]
