# Generated by Django 3.0 on 2019-12-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
