# Generated by Django 3.0 on 2020-01-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
