# Generated by Django 3.0 on 2020-01-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_delete_shoppingcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincart',
            options={'ordering': ['product']},
        ),
    ]
