# Generated by Django 3.0.1 on 2020-01-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200120_1746'),
        ('shop', '0007_auto_20200119_1601'),
    ]

    operations = [
    ]
