# Generated by Django 3.0.1 on 2020-01-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_merge_20200120_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincart',
            options={},
        ),
    ]
