# Generated by Django 3.0.1 on 2020-01-20 19:35

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200120_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='http://placehold.it/700x400', null=True, upload_to=shop.models.get_image_path),
        ),
    ]
