# Generated by Django 3.0.1 on 2020-01-21 12:35

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200120_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_long',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to=shop.models.get_image_path),
        ),
    ]
